### ISSUE TITLE
Doesn't seem to be working with `tmux 3.4`

### ISSUE THREAD

**Issue by farzadmf** [wfxr/tmux-fzf-url#40] opened 2024-02-15 19:41 UTC
Hi, I use this plugin a million times per day, but it seems like it doesn't work anymore after the recent `tmux 3.4` update.

I narrowed down the issue to be when there are actually URLs in shell history.

What I mean is that:
- If there are no URLs in the history, it properly runs and says "no URLs found"
- If there _are_ URLs, when I press the keybinding (I'm using the default `prefix + u`), nothing happens

Let me know if I can provide more information to help troubleshoot the issue

**Comment by Tony-Sol** [comment] 2024-02-16 13:12
Same here

**Comment by Carl-ZLJ** [comment] 2024-02-16 14:10
same here

**Comment by farzadmf** [comment] 2024-02-17 03:31
@wfxr would you be able to take a look please?

**Comment by farzadmf** [comment] 2024-02-18 13:47
I found the issue/workaround, and I created my [own fork](https://github.com/farzadmf/tmux-fzf-url). Since I'm not sure if that's a valid solution, I'm not gonna create a PR.

The split is now bigger, but personally I don't care as long as it works :/

**Comment by wfxr** [comment] 2024-02-19 02:31
Hi @farzadmf It seems I cannot reproduce this on my mac with tmux v3.4. I suspect this problem may be related to the fzf. Can you check the version of your fzf? It's 0.46.1 on my machine.

**Comment by farzadmf** [comment] 2024-02-19 02:38
Hey @wfxr , thanks for you reply. Seems like to be the same version for me (`0.46.1 (brew)` on my Mac).

The weird thing is that if I run the `fzf-tmux ...` command directly in the temrinal, it displays `fzf` window (BUT, seems like it's ignoring the `-d 35%` option and showing it full-screen, so that might be something)

**Comment by wfxr** [comment] 2024-02-19 02:45
@farzadmf thanks for your quick reply! I forgot that I had overridden the fzf-url-fzf-options:

```
set -g @fzf-url-fzf-options '-w 100% -h 50% --multi -0 --no-preview'
```

I can reproduce the problem after commented the above line in `tmux.conf`. And removing `-d 35%` also works for me.

**Comment by farzadmf** [comment] 2024-02-19 02:49
Oh cool, that setting seems to be very useful (more useful than the default bottom split that doesn't seem to be working anymore), so I'm gonna use that.

Do you know why it doesn't work with `-d 35%`?

**Comment by wfxr** [comment] 2024-02-19 02:54
> Do you know why it doesn't work with `-d 35%`?

I also don't know why it doesn't work. Maybe it's related to [this issue](https://github.com/junegunn/fzf/issues/3635)?

**Comment by wfxr** [comment] 2024-02-19 02:55
I'm going to replace the default settings with the following to workaround this problem, what do you think? @farzadmf @Tony-Sol @Carl-ZLJ 

```
set -g @fzf-url-fzf-options '-w 100% -h 50% --multi -0 --no-preview'
```

**Comment by farzadmf** [comment] 2024-02-19 02:56
Sounds good to me; as I mentioned, it's much better than the bottom split that I've been using. Glad that the issue happened for me to learn about this 😛

**Comment by wfxr** [comment] 2024-02-19 03:02
Merged. You can update and have a try.

**Comment by farzadmf** [comment] 2024-02-19 03:10
Works for me; gonna close the issue as the original issue I had is resolved; thank you @wfxr for looking into it.

I have a question though: seems like if I set the option in my config using `set -g @fzf-url-fzf-options '...'`, I get a pop-up window showing the URLs, but if I don't (and use the default), I get a split.

I personally prefer the pop-up, so I'm keeping the option in my config, but it's confusing for me as the option value is the same, but giving different results 🤔 Does it make sense? I'm probably missing something!

**Closed** 2024-02-19 03:10 UTC

**Comment by wfxr** [comment] 2024-02-19 03:30
> I have a question though: seems like if I set the option in my config using set -g @fzf-url-fzf-options '...', I get a pop-up window showing the URLs, but if I don't (and use the default), I get a split.

Weird, I always see the pop-up window regardless of whether setting it explicitly. You can go to the plugin directory to check whether it has been updated to the latest commit.

**Comment by farzadmf** [comment] 2024-02-19 03:35
Well, my bad, sorry 🤦 ; I had changes when I was testing to figure out the issue, and it couldn't pull the changes, so all good now
